steps:
  # build the container image
  - id: 'build_container'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME',
        '.',
        '--build-arg',
        'BUILD_MODE=$_BUILD_MODE',
      ]
  # push the container image to Container Registry
  - id: 'push_container_to_registry'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME']
  # Deploy container image to Cloud Run
  - id: 'deploy_registry_to_cloudrun'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        '$REPO_NAME-$_BUILD_MODE',
        '--image',
        'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
        '--port',
        '8080',
        '--quiet',
      ]
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME
